# Generated by Django 2.0.1 on 2018-01-27 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=8)),
                ('graduating_year', models.IntegerField(max_length=4)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('draft_status', models.BooleanField()),
                ('project_title', models.CharField(max_length=200)),
                ('project_summary', models.CharField(max_length=500)),
                ('project_notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectExplorer.Member')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectExplorer.ProjectManager'),
        ),
    ]
