# Generated by Django 2.0.1 on 2018-01-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectExplorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='graduating_year',
            field=models.IntegerField(),
        ),
    ]
